language: objective-c
osx_image: xcode9.2

cache:
  directories:
    - Carthage
    - Inspector/node_modules

script: ./Scripts/build.sh

env:
  global:
    - PLATFORM=ios
    - SDK=sim

jobs:
  include:
    - stage: tests
      env: ACTION=build TARGET=runner
    - stage:
      env: ACTION=build TARGET=runner SDK=device

    - stage:
      env: ACTION=analyze TARGET=lib
    - stage:
      env: ACTION=analyze TARGET=runner

    - stage:
      env: ACTION=unit_test DEST=iphone TARGET=lib
    - stage:
      env: ACTION=unit_test DEST=ipad TARGET=lib

    - stage:
      env: ACTION=int_test_1 DEST=iphone TARGET=lib
    - stage:
      env: ACTION=int_test_2 DEST=iphone TARGET=lib
    - stage:
      env: ACTION=int_test_3 DEST=iphone TARGET=lib

    - stage:
      env: ACTION=int_test_1 DEST=ipad TARGET=lib
    - stage:
      env: ACTION=int_test_2 DEST=ipad TARGET=lib
    - stage:
      env: ACTION=int_test_3 DEST=ipad TARGET=lib
